[Interface]
Address = {{ vpn_ip}}/{{ vpn_netlen }}
ListenPort = {{ listen_port }}
PrivateKey = {{ private_key }}
PostUp = /etc/wireguard/scripts/post-up.sh
PostDown = /etc/wireguard/scripts/post-down.sh

{% for peer in peers %}
[Peer]
PublicKey  = {{ peer.public_key }}
Endpoint   = {{ peer.public_ip }}:{{ listen_port }}
AllowedIPs = {{ peer.vpn_ip }}/32,{{ peer.cidr_block }}
{% endfor %}

